### ISSUE TITLE
Adapt and publish all algorithm images

### ISSUE THREAD

**Issue by CodeLionX** [TimeEval/TimeEval-algorithms#26]
Base images (#21)

- [x] java-base
- [x] python2-base
- [x] python3-base
- [x] python36-base
- [x] r-base
- [x] r4-base (fix: #36)
- [x] rust-base

Intermediate images (#22)

- [x] pyod
- [x] python3-torch
- [x] timeeval-test-algorithm
- [x] tsmp

Algorithm images:

- [x] arima (#28)
- [x] autoencoder (#28)
- [x] bagel (#28)
- [x] baseline_increasing (#28)
- [x] baseline_normal (#28)
- [x] baseline_random (#28)
- [x] cblof (#28)
- [x] cof (#28)
- [x] copod (#28)
- [x] dae (#28)
- [x] damp (#28)
- [x] dbstream (#33, #35)
- [x] deepant (#28)
- [x] deepnap (#28)
- [x] donut (#28)
- [x] dspot (#28)
- [x] dwt_mlead (#28)
- [x] eif (#34)
- [x] encdec_ad (#34)
- [x] ensemble_gi (#34)
- [x] fast_mcd (#34)
- [x] fft (#34)
- [x] generic_rf (#34)
- [x] generic_xgb (#34)
- [x] grammarviz3 (#34)
- [x] grammarviz3_multi (#34)
- [x] hbos (#34)
- [x] health_esn (#34)
- [x] hif (#34)
- [x] hotsax (#34)
- [x] hybrid_knn (#34)
- [x] if_lof (#34)
- [x] iforest (#34)
- [x] img_embedding_cae (#34)
- [x] kmeans (#23, #24)
- [x] knn (#37)
- [x] laser_dbn (#37)
- [x] left_stampi (#37)
- [x] lof (#37)
- [x] lstm_ad (#37)
- [x] lstm_vae (#37)
- [x] median_method (#37)
- [x] mscred (#37)
- [x] mstamp (#37)
- [x] mtad_gat (#37)
- [x] multi_hmm (#37)
- [x] multi_subsequence_lof (#37)
- [x] mvalmod (#37)
- [x] norma (#37)
- [x] normalizing_flows (#37)
- [x] novelty_svr (#37)
- [x] numenta_htm (#37)
- [x] ocean_wnn (#39)
- [x] omnianomaly (#39)
- [x] pcc (#39)
- [x] pci (#39)
- [x] phasespace_svm (#39)
- [x] pst (#33, #35)
- [x] random_black_forest (#39)
- [x] robust_pca (#39)
- [x] sand (#39)
- [x] sarima (#39)
- [x] series2graph (#39)
- [x] s_h_esd (#39)
- [x] sr (#39)
- [x] sr_cnn (#39)
- [x] ssa (#39)
- [x] stamp (#39)
- [x] stomp (#39)
- [x] subsequence_fast_mcd (#39)
- [x] subsequence_knn (#39)
- [x] subsequence_if (#39)
- [x] subsequence_lof (#39)
- [x] tanogan (#39)
- [x] tarzan (#39)
- [x] telemanom (#39)
- [x] torsk (#39)
- [x] triple_es (#39)
- [x] ts_bitmap (#39)
- [x] valmod (#39)

**Comment by CodeLionX** [comment]
I'll work on [a-d].* next
